# Generated by Django 5.1.1 on 2024-10-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bunga_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunga',
            name='stocks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
