# Generated by Django 5.1.1 on 2024-10-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bunga_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunga',
            name='img_url',
            field=models.URLField(default='https://ecentral.my/wp-content/uploads/2024/09/daisy-1024x768.jpg'),
            preserve_default=False,
        ),
    ]
